version: "3.7"
services:
  frontend:
    build: .
    command: npm run start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
